/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;

/**
 *
 * @author Quoc An
 */
public class Exam extends javax.swing.JFrame {

    /**
     * Creates new form Exam
     */
    
    public ButtonGroup G;
    public Exam() {
        initComponents();
        this.setTitle("Quiz Exam");
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        
        // set the time with "limit time" and countdown
        
        jButton_next.putClientProperty( "JButton.buttonType", "roundRect" );
        jButton_next.putClientProperty( "JButton.focusWidth", 1 );
        jButton_prev.putClientProperty( "JButton.buttonType", "roundRect" );
        jButton_prev.putClientProperty( "JButton.focusWidth", 1 );
        jButton_finish.putClientProperty( "JButton.buttonType", "roundRect" );
        jButton_finish.putClientProperty( "JButton.focusWidth", 1 );
        
        jRadioButton_answer_1.setActionCommand("A");
        jRadioButton_answer_2.setActionCommand("B");
        jRadioButton_answer_3.setActionCommand("C");
        jRadioButton_answer_4.setActionCommand("D");
        
        G = new ButtonGroup();
        G.add(jRadioButton_answer_1);
        G.add(jRadioButton_answer_2);
        G.add(jRadioButton_answer_3);
        G.add(jRadioButton_answer_4);
        
        // if (time == 0)
        //      then finish quiz and save all the answer
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton_answer_1 = new javax.swing.JRadioButton();
        jRadioButton_answer_2 = new javax.swing.JRadioButton();
        jRadioButton_answer_3 = new javax.swing.JRadioButton();
        jRadioButton_answer_4 = new javax.swing.JRadioButton();
        jButton_prev = new javax.swing.JButton();
        jButton_next = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton_finish = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Question ?:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Question ......................");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jRadioButton_answer_1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jRadioButton_answer_1.setText("ahha");
        jRadioButton_answer_1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jRadioButton_answer_1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jRadioButton_answer_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_answer_1ActionPerformed(evt);
            }
        });

        jRadioButton_answer_2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jRadioButton_answer_2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jRadioButton_answer_2.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jRadioButton_answer_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_answer_2ActionPerformed(evt);
            }
        });

        jRadioButton_answer_3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jRadioButton_answer_3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jRadioButton_answer_3.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jRadioButton_answer_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_answer_3ActionPerformed(evt);
            }
        });

        jRadioButton_answer_4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jRadioButton_answer_4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jRadioButton_answer_4.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jRadioButton_answer_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_answer_4ActionPerformed(evt);
            }
        });

        jButton_prev.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jButton_prev.setText("Previous");
        jButton_prev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_prevActionPerformed(evt);
            }
        });

        jButton_next.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jButton_next.setText("Next");
        jButton_next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_nextActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Time : 00.00.00");

        jButton_finish.setBackground(new java.awt.Color(255, 255, 102));
        jButton_finish.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jButton_finish.setForeground(new java.awt.Color(51, 51, 51));
        jButton_finish.setText("Finish");
        jButton_finish.setBorderPainted(false);
        jButton_finish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_finishActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jRadioButton_answer_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButton_answer_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButton_answer_3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButton_answer_4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jButton_prev, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_next, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 491, Short.MAX_VALUE)
                        .addComponent(jButton_finish, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton_answer_1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton_answer_2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton_answer_3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton_answer_4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_prev, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_next, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_finish, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton_answer_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_answer_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_answer_3ActionPerformed

    private void jRadioButton_answer_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_answer_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_answer_4ActionPerformed

    private void jRadioButton_answer_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_answer_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_answer_2ActionPerformed

    private void jButton_finishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_finishActionPerformed
        // TODO add your handling code here:
        this.dispose();
        
        //save all the answer and package it
        //then push it to server to check the answer
        
        
        
        
        
        //return to show result
        Result result = new Result();
        result.setVisible(true);
        this.dispose();
        //set data to label
    }//GEN-LAST:event_jButton_finishActionPerformed

    private void jButton_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_nextActionPerformed
        // TODO add your handling code here:
        
        //save selection of the question
        System.out.println(G.getSelection().getActionCommand());
        
        //then push next question in the label and radion button, num of question
        G.clearSelection();
        jRadioButton_answer_1.setText("");
        jRadioButton_answer_2.setText("");
        jRadioButton_answer_3.setText("");
        jRadioButton_answer_4.setText("");
        
    }//GEN-LAST:event_jButton_nextActionPerformed

    private void jRadioButton_answer_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_answer_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_answer_1ActionPerformed

    private void jButton_prevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_prevActionPerformed
        // TODO add your handling code here:
        
        //save selection of the question
        System.out.println(G.getSelection().getActionCommand());
        
        //then push previous question in the label and radion button, num of question
        G.clearSelection();
        jRadioButton_answer_1.setText("");
        jRadioButton_answer_2.setText("");
        jRadioButton_answer_3.setText("");
        jRadioButton_answer_4.setText("");
    }//GEN-LAST:event_jButton_prevActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatLightLaf.setup();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exam().setVisible(true);
                
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_finish;
    private javax.swing.JButton jButton_next;
    private javax.swing.JButton jButton_prev;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton jRadioButton_answer_1;
    private javax.swing.JRadioButton jRadioButton_answer_2;
    private javax.swing.JRadioButton jRadioButton_answer_3;
    private javax.swing.JRadioButton jRadioButton_answer_4;
    // End of variables declaration//GEN-END:variables
}
