/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.Arrays;
import java.util.Date;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author Quoc An
 */
public class Signup extends javax.swing.JFrame {

    /**
     * Creates new form Signup
     */
    ButtonGroup G;
    public Signup() {
        initComponents();
        this.setTitle("Quiz Exam");
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        jFormattedTextField_email.putClientProperty( "JComponent.roundRect", true );
        jFormattedTextField_email.putClientProperty( "JTextField.placeholderText","Email");
        
        jFormattedTextField_username.putClientProperty( "JComponent.roundRect", true );
        jFormattedTextField_username.putClientProperty( "JTextField.placeholderText","Username");
        
        jFormattedTextField_fullname.putClientProperty( "JComponent.roundRect", true );
        jFormattedTextField_fullname.putClientProperty( "JTextField.placeholderText","Fullname");
        
        jXDatePicker_birth.putClientProperty( "JComponent.roundRect", true );
        jXDatePicker_birth.putClientProperty( "JTextField.placeholderText","date");
        jXDatePicker_birth.setFormats("dd/MM/yyyy");

        jPasswordField_password.putClientProperty( "JComponent.roundRect", true );
        jPasswordField_password.putClientProperty( "JTextField.placeholderText","Password");
        
        jButton_cancel.putClientProperty( "JButton.buttonType", "roundRect" );
        
        jButton_submit.putClientProperty( "JButton.buttonType", "roundRect" );
        
        G = new ButtonGroup();
        G.add(jRadioButton_male);
        G.add(jRadioButton_female);
        
        /* 
        if(jRadioButton_male.isSelected()){
            //TODO
        }else if(jRadioButton_female.isSelected()){
            //TODO
        }else{
            JOptionPane.showMessageDialog(this, "error");
        }
        */
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        datePickerAddon1 = new org.jdesktop.swingx.plaf.DatePickerAddon();
        datePickerAddon2 = new org.jdesktop.swingx.plaf.DatePickerAddon();
        datePickerAddon3 = new org.jdesktop.swingx.plaf.DatePickerAddon();
        datePickerCellEditor1 = new org.jdesktop.swingx.table.DatePickerCellEditor();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jFormattedTextField_username = new javax.swing.JFormattedTextField();
        jFormattedTextField_fullname = new javax.swing.JFormattedTextField();
        jFormattedTextField_email = new javax.swing.JFormattedTextField();
        jXDatePicker_birth = new org.jdesktop.swingx.JXDatePicker();
        jRadioButton_male = new javax.swing.JRadioButton();
        jRadioButton_female = new javax.swing.JRadioButton();
        jLabel_gender = new javax.swing.JLabel();
        jLabel_username = new javax.swing.JLabel();
        jLabel_fullname = new javax.swing.JLabel();
        jLabel_password = new javax.swing.JLabel();
        jLabel_email = new javax.swing.JLabel();
        jLabel_birth = new javax.swing.JLabel();
        jPasswordField_password = new javax.swing.JPasswordField();
        jButton_submit = new javax.swing.JButton();
        jButton_cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Create account");

        jFormattedTextField_username.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jFormattedTextField_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField_usernameActionPerformed(evt);
            }
        });

        jFormattedTextField_fullname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jFormattedTextField_fullname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField_fullnameActionPerformed(evt);
            }
        });

        jFormattedTextField_email.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jFormattedTextField_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField_emailActionPerformed(evt);
            }
        });

        jXDatePicker_birth.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jRadioButton_male.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jRadioButton_male.setText("Male");
        jRadioButton_male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_maleActionPerformed(evt);
            }
        });

        jRadioButton_female.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jRadioButton_female.setText("Female");

        jLabel_gender.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_gender.setText("Gender");

        jLabel_username.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_username.setText("Username");

        jLabel_fullname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_fullname.setText("Fullname");

        jLabel_password.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_password.setText("Password");

        jLabel_email.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_email.setText("Email");

        jLabel_birth.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_birth.setText("Birthday");

        jPasswordField_password.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jButton_submit.setBackground(new java.awt.Color(34, 133, 225));
        jButton_submit.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButton_submit.setForeground(new java.awt.Color(255, 255, 255));
        jButton_submit.setText("Submit");
        jButton_submit.setBorderPainted(false);
        jButton_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_submitActionPerformed(evt);
            }
        });

        jButton_cancel.setBackground(new java.awt.Color(255, 102, 102));
        jButton_cancel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButton_cancel.setForeground(new java.awt.Color(255, 255, 255));
        jButton_cancel.setText("Cancel");
        jButton_cancel.setBorderPainted(false);
        jButton_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPasswordField_password, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_birth)
                    .addComponent(jLabel_email)
                    .addComponent(jLabel_password)
                    .addComponent(jFormattedTextField_email, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField_fullname, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(113, 113, 113))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jFormattedTextField_username, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(70, 70, 70)))
                    .addComponent(jLabel_gender)
                    .addComponent(jLabel_username)
                    .addComponent(jLabel_fullname)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jButton_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_submit, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jRadioButton_male)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jRadioButton_female))
                        .addComponent(jXDatePicker_birth, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel_username)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFormattedTextField_username, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_password)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField_password, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_fullname)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFormattedTextField_fullname, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_email)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFormattedTextField_email, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_birth)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jXDatePicker_birth, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_gender)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton_male)
                    .addComponent(jRadioButton_female))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_submit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFormattedTextField_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField_usernameActionPerformed

    private void jFormattedTextField_fullnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField_fullnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField_fullnameActionPerformed

    private void jFormattedTextField_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField_emailActionPerformed

    private void jRadioButton_maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_maleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_maleActionPerformed

    private void jButton_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Login login = new Login();
        login.setVisible(true);
    }//GEN-LAST:event_jButton_cancelActionPerformed

    private void jButton_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_submitActionPerformed
        // TODO add your handling code here:
        if(jFormattedTextField_email.getText().length() != 0 && 
                jFormattedTextField_fullname.getText().length() != 0 &&
                jFormattedTextField_username.getText().length() != 0 &&
                jPasswordField_password.getPassword().length != 0 &&
                jXDatePicker_birth.getDate().toString().length() != 0 &&
                G.getSelection().isSelected() != false){
            String username = jFormattedTextField_username.getText();
            String email = jFormattedTextField_email.getText();
            String fullname = jFormattedTextField_fullname.getText();
            String pass = Arrays.toString(jPasswordField_password.getPassword());
            Date birth = jXDatePicker_birth.getDate();
            boolean gender;
            if(jRadioButton_male.isSelected()){
                gender = true; //male Selected
            }else if(jRadioButton_female.isSelected()){
                gender = false; //female Selected
            }
            JOptionPane.showMessageDialog(this, "Created account success!");
            this.dispose();
            Login login = new Login();
            login.setVisible(true);
            
            
            //TODO signup
            
            
            
        }else{
            JOptionPane.showMessageDialog(this, "Do not leave fields blank!");
        }
    }//GEN-LAST:event_jButton_submitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatLightLaf.setup();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private org.jdesktop.swingx.plaf.DatePickerAddon datePickerAddon1;
    private org.jdesktop.swingx.plaf.DatePickerAddon datePickerAddon2;
    private org.jdesktop.swingx.plaf.DatePickerAddon datePickerAddon3;
    private org.jdesktop.swingx.table.DatePickerCellEditor datePickerCellEditor1;
    private javax.swing.JButton jButton_cancel;
    private javax.swing.JButton jButton_submit;
    private javax.swing.JFormattedTextField jFormattedTextField_email;
    private javax.swing.JFormattedTextField jFormattedTextField_fullname;
    private javax.swing.JFormattedTextField jFormattedTextField_username;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_birth;
    private javax.swing.JLabel jLabel_email;
    private javax.swing.JLabel jLabel_fullname;
    private javax.swing.JLabel jLabel_gender;
    private javax.swing.JLabel jLabel_password;
    private javax.swing.JLabel jLabel_username;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField_password;
    private javax.swing.JRadioButton jRadioButton_female;
    private javax.swing.JRadioButton jRadioButton_male;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker_birth;
    // End of variables declaration//GEN-END:variables
}
