/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import java.awt.Image;
import java.awt.Window;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import org.json.JSONObject;

/**
 *
 * @author Quoc An
 */
public class UserInformation extends javax.swing.JPanel {

    /**
     * Creates new form UserInformation
     */
    JFrame changePwd;
    public UserInformation(JSONObject json) {
        initComponents();
        BufferedImage img = null;
        BufferedImage img_edit = null;
        try {
            img = ImageIO.read(getClass().getResource("/GUI/Image/user.png"));
            img_edit = ImageIO.read(getClass().getResource("/GUI/Image/edit.png"));
        } catch (IOException e) {
            e.printStackTrace();
        }
        Image dimg = img.getScaledInstance(160, 160,Image.SCALE_SMOOTH);
        ImageIcon imageIcon = new ImageIcon(dimg);
        jLabel1.setIcon(imageIcon);
        
        Image dimg_edit = img_edit.getScaledInstance(30, 30,Image.SCALE_SMOOTH);
        ImageIcon imageIcon_edit = new ImageIcon(dimg_edit);
        jButton_edit.setIcon(imageIcon_edit);
        
        jButton_changePass.putClientProperty("JButton.buttonType", "borderless");
        jButton_logout.putClientProperty("JButton.buttonType", "borderless");
        
        //set data to jlabel
        
        jLabel_username.setText(json.getString("username"));
        jLabel_fullname.setText(json.getString("fullname"));
        jLabel_email.setText(json.getString("email"));
        jLabel_birth.setText(json.getString("birth"));
        jLabel_gender.setText(json.getString("gender"));
        jLabel_blockStatus.setText(json.getString("blockStatus"));
        
        jButton_edit.addActionListener(new ActionListener() {
         public void actionPerformed(ActionEvent e) {
             try {
                 EditUserInfor edit = new EditUserInfor(json);
                 edit.setVisible(true);
                 
             } catch (ParseException ex) {
                 Logger.getLogger(UserInformation.class.getName()).log(Level.SEVERE, null, ex);
             }
         }
      });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel_username = new javax.swing.JLabel();
        jLabel_email = new javax.swing.JLabel();
        jLabel_fullname = new javax.swing.JLabel();
        jLabel_birth = new javax.swing.JLabel();
        jLabel_gender = new javax.swing.JLabel();
        jLabel_blockStatus = new javax.swing.JLabel();
        jButton_edit = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton_changePass = new javax.swing.JButton();
        jButton_logout = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1183, 659));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setMaximumSize(new java.awt.Dimension(0, 0));
        jPanel1.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(1503, 1037));
        jPanel1.setVerifyInputWhenFocusTarget(false);
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(650, 300));
        jPanel2.setMinimumSize(new java.awt.Dimension(650, 300));
        jPanel2.setPreferredSize(new java.awt.Dimension(450, 300));
        jPanel2.setRequestFocusEnabled(false);
        jPanel2.setVerifyInputWhenFocusTarget(false);
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Username :");
        jLabel2.setMaximumSize(new java.awt.Dimension(125, 25));
        jLabel2.setMinimumSize(new java.awt.Dimension(125, 25));
        jLabel2.setPreferredSize(new java.awt.Dimension(125, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(130, 5, 0, 0);
        jPanel2.add(jLabel2, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Full name :");
        jLabel3.setMaximumSize(new java.awt.Dimension(125, 25));
        jLabel3.setMinimumSize(new java.awt.Dimension(125, 25));
        jLabel3.setPreferredSize(new java.awt.Dimension(125, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 5, 0, 0);
        jPanel2.add(jLabel3, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Email : ");
        jLabel4.setMaximumSize(new java.awt.Dimension(125, 25));
        jLabel4.setMinimumSize(new java.awt.Dimension(125, 25));
        jLabel4.setPreferredSize(new java.awt.Dimension(125, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 5, 0, 0);
        jPanel2.add(jLabel4, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Birth :");
        jLabel5.setMaximumSize(new java.awt.Dimension(125, 25));
        jLabel5.setMinimumSize(new java.awt.Dimension(125, 25));
        jLabel5.setPreferredSize(new java.awt.Dimension(125, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 5, 0, 0);
        jPanel2.add(jLabel5, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Gender :");
        jLabel6.setMaximumSize(new java.awt.Dimension(125, 25));
        jLabel6.setMinimumSize(new java.awt.Dimension(125, 25));
        jLabel6.setPreferredSize(new java.awt.Dimension(125, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 5, 0, 0);
        jPanel2.add(jLabel6, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Block Status :");
        jLabel7.setMaximumSize(new java.awt.Dimension(125, 25));
        jLabel7.setMinimumSize(new java.awt.Dimension(125, 25));
        jLabel7.setPreferredSize(new java.awt.Dimension(125, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 5, 132, 0);
        jPanel2.add(jLabel7, gridBagConstraints);

        jLabel_username.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_username.setText("lyquocan17");
        jLabel_username.setName(""); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 129;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(130, 6, 0, 0);
        jPanel2.add(jLabel_username, gridBagConstraints);

        jLabel_email.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_email.setText("lyquocan171@gmail.com");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 19;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 6, 0, 0);
        jPanel2.add(jLabel_email, gridBagConstraints);

        jLabel_fullname.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_fullname.setText("ly quoc an");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 139;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 6, 0, 0);
        jPanel2.add(jLabel_fullname, gridBagConstraints);

        jLabel_birth.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_birth.setText("17/01/2001");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 127;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 6, 0, 0);
        jPanel2.add(jLabel_birth, gridBagConstraints);

        jLabel_gender.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_gender.setText("Male");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 183;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 6, 0, 0);
        jPanel2.add(jLabel_gender, gridBagConstraints);

        jLabel_blockStatus.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel_blockStatus.setText("No");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 197;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 6, 132, 0);
        jPanel2.add(jLabel_blockStatus, gridBagConstraints);

        jButton_edit.setText(" ");
        jButton_edit.setBorderPainted(false);
        jButton_edit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_edit.setMaximumSize(new java.awt.Dimension(35, 35));
        jButton_edit.setMinimumSize(new java.awt.Dimension(35, 35));
        jButton_edit.setPreferredSize(new java.awt.Dimension(35, 35));
        jButton_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_editActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(120, 0, 0, 50);
        jPanel2.add(jButton_edit, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(134, 0, 129, 5);
        jPanel1.add(jPanel2, gridBagConstraints);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setMaximumSize(new java.awt.Dimension(300, 300));
        jPanel3.setMinimumSize(new java.awt.Dimension(300, 300));
        jPanel3.setName(""); // NOI18N
        jPanel3.setPreferredSize(new java.awt.Dimension(300, 300));
        jPanel3.setRequestFocusEnabled(false);
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel1.setRequestFocusEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(30, 89, 0, 89);
        jPanel3.add(jLabel1, gridBagConstraints);

        jButton_changePass.setBackground(new java.awt.Color(255, 204, 51));
        jButton_changePass.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_changePass.setForeground(new java.awt.Color(51, 51, 51));
        jButton_changePass.setText("Change Password");
        jButton_changePass.setBorderPainted(false);
        jButton_changePass.setFocusPainted(false);
        jButton_changePass.setMaximumSize(new java.awt.Dimension(148, 35));
        jButton_changePass.setMinimumSize(new java.awt.Dimension(148, 35));
        jButton_changePass.setPreferredSize(new java.awt.Dimension(148, 35));
        jButton_changePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_changePassActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(18, 89, 0, 89);
        jPanel3.add(jButton_changePass, gridBagConstraints);

        jButton_logout.setBackground(new java.awt.Color(255, 51, 51));
        jButton_logout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_logout.setForeground(new java.awt.Color(255, 255, 255));
        jButton_logout.setText("Logout");
        jButton_logout.setBorderPainted(false);
        jButton_logout.setMaximumSize(new java.awt.Dimension(148, 35));
        jButton_logout.setMinimumSize(new java.awt.Dimension(148, 35));
        jButton_logout.setPreferredSize(new java.awt.Dimension(148, 35));
        jButton_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_logoutActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(18, 89, 50, 89);
        jPanel3.add(jButton_logout, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(134, 5, 129, 0);
        jPanel1.add(jPanel3, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        jPanel1.getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_changePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_changePassActionPerformed
        // TODO add your handling code here:
        changePwd = new ChangePassword();
        changePwd.setVisible(true);
        
    }//GEN-LAST:event_jButton_changePassActionPerformed

    private void jButton_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_logoutActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton_logoutActionPerformed

    private void jButton_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_editActionPerformed
        // TODO add your handling code here:
       Window window = SwingUtilities.getWindowAncestor(this);
       window.dispose();
       this.setVisible(false);
        
    }//GEN-LAST:event_jButton_editActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_changePass;
    private javax.swing.JButton jButton_edit;
    private javax.swing.JButton jButton_logout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel_birth;
    private javax.swing.JLabel jLabel_blockStatus;
    private javax.swing.JLabel jLabel_email;
    private javax.swing.JLabel jLabel_fullname;
    private javax.swing.JLabel jLabel_gender;
    private javax.swing.JLabel jLabel_username;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
